
	/*1)    CONSIDERO TRE NUMERI INSERITI DALL UTENTE,
	LI STAMPERO IN CONSOLE DAL PIU PICCOLO AL PIU GRANDE */

	/*2)CONSIDERO LA STRINGA INSERITA
	STAMPO IN CONSOLE.LOG IL NOME DELLA VARIABILE SEGUITO DA .LENGTH */

    /*3)
	CONSIDERO LE STRINGHE ARRIVATI,ALLA STRINGA FINE
	STAMPO CON CONSOLE.LOG USANDO USANDO UNA TERZA VARIABILE CHE MI
PERMETTE L’OPERAZIONE DI UNIONE DELLE STRINGHE AD ESEMPIO .CONCAT O
USANDO SEMPLICEMENTE IL SEGNO “+”. */


    /*4)
	CONSIDERO I DIECI NUMERI DELL UTENTE,CALCOLO IL VALORE MINIMO E IL VALORE MASSIMO :
DICHIARANDO UNA VARIABILE CON UN ARRAY DI NUMERI 
SCRIVERO IL CONSOLE.LOG UTILIZZANDO NEL CASO MINIMO (MATH.MIN(...VARIABILE))
E NEL CASO MASSIMO (MATH.MAX(...VARIABILE)) */

	
    /*5)
	CONSIDERO I NUMERI DA UNO A MILLE E PROVO AD ESEGUIRE L’OPERAZIONE 
	ATTRAVERSO UNA FUNZIONE STAMPANDO LA SOMMA IN CONSOLE DEL QUADRATO DI OGNI NUMERO MENO IL SUO PREDECESSORE. */

/*6)
CONSIDERO UN SECONDO NUMERO FIN QUANDO NON SUPERI QUELLO DICHIARATO INIZIALMENTE E RIPETERO QUEST 
ESTRAZIONE CON UN CICLO FOR STOPPANDOLO ALL ARRIVO DELL OBIETTIVO,CONTANDO I NUMERI PARI ESTRATTI,STAMPERO IN CONSOLE IL RISULTATO */


